

services:
  artists-db:
    image: postgres:15-alpine
    container_name: rebelway-artists-db
    ports:
      - "5432:5432"
    env_file:
      - ./services/artist-service/.env 
    volumes:
      - artists-data:/var/lib/postgresql/data

  songs-db:
    image: postgres:15-alpine
    container_name: rebelway-songs-db
    ports:
      - "5433:5432"
    env_file:
      - ./services/song-service/.env 
    volumes:
      - songs-data:/var/lib/postgresql/data

  artist-service:
      image: node:24-alpine
      container_name: rebelway-artist-service
      working_dir: /app
      volumes:
        - .:/app
        - /app/node_modules
      command: sh -c "npm install && npm run dev:artist"
      ports:
        - "4001:4001"
      env_file:
        - ./services/artist-service/.env # Magia: Lee tu .env local en secreto
      environment:
        - NODE_ENV=development
        - PORT=4001
      depends_on:
        - artists-db
  song-service:
      image: node:24-alpine
      container_name: rebelway-song-service
      working_dir: /app
      volumes:
        - .:/app
        - /app/node_modules
      command: sh -c "npm install && npm run dev:song"
      ports:
        - "4002:4002"
      env_file:
        - ./services/song-service/.env # Lee su propio .env local
      environment:
        - NODE_ENV=development
        - PORT=4002
      depends_on:
        - songs-db

volumes:
  artists-data:
  songs-data: