services:
  songs-db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432" 

  songs-app:
    build: .
    ports:
      - "4002:4002"
    env_file:
      - .env 
    depends_on:
      - songs-db